version: "3.8"

services:
  db:
    image: pos-db
    container_name: pos-db
    build:
      context: .
      target: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pos
    ports:
      - "5432:5432"